/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class torsec_ra_cassandra_db_PackagesVersionTypeDEB */

#ifndef _Included_torsec_ra_cassandra_db_PackagesVersionTypeDEB
#define _Included_torsec_ra_cassandra_db_PackagesVersionTypeDEB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     torsec_ra_cassandra_db_PackagesVersionTypeDEB
 * Method:    filevercmp_deb
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_torsec_ra_cassandra_db_PackagesVersionTypeDEB_filevercmp_1deb
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
