/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class torsec_ra_cassandra_db_PackagesVersionType */

#ifndef _Included_torsec_ra_cassandra_db_PackagesVersionType
#define _Included_torsec_ra_cassandra_db_PackagesVersionType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     torsec_ra_cassandra_db_PackagesVersionType
 * Method:    filevercmp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_torsec_ra_cassandra_db_PackagesVersionType_filevercmp
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
